RC1 changes
neow3j/neow3j pull request #468
Opened 2021-03-11 17:24 UTC by mialbu

2021-03-16 09:27 UTC, csmuller requested changes

2021-03-16 09:27 UTC, csmuller commented on compiler/src/test-integration/java/io/neow3j/compiler/ContractTest.java
> +        waitUntilBlockCountIsGreaterThanZero(neow3j);
Do we need to keep this?

2021-03-16 18:47 UTC, csmuller requested changes

2021-03-17 09:06 UTC, mialbu commented on core/src/main/java/io/neow3j/contract/ContractParameter.java
> +    public static class ContractParameterSerializer extends StdSerializer<ContractParameter> {
This was committed unintentionally, I'll change it back.

2021-03-17 09:06 UTC, mialbu commented on core/src/main/java/io/neow3j/contract/ContractParameter.java
> +        public void serializeParameter(ContractParameter p, JsonGenerator gen) throws IOException {
This was committed unintentionally, I'll change it back.

2021-03-18 09:38 UTC, csmuller approved these changes

2021-03-18 09:40 UTC, merged