Neo 3.2.0 updates
neow3j/neow3j pull request #758
Opened 2022-04-14 08:50 UTC by mialbu

2022-04-22 15:27 UTC, gsmachado commented
This will be a large one... 😅  🚀  💪

2022-04-22 15:27 UTC, gsmachado commented
This will be a large one... 😅  🚀  💪

2022-04-27 10:03 UTC, mialbu commented
#759 will not be included in this PR due to issues when accessing a list entry when a signer with witness scope `rules` is present. #759 will be handled separately in PR #764.

2022-04-27 16:44 UTC, csmuller requested changes
Good work!

I pushed two minor changes directly.

Can you add one integration test in `Neow3jReadOnlyIntegrationTest`or `Neow3jWriteIntegrationTest` that uses a `WitnessRule` in its witness? Just to make sure that we are really passing the correctly serialised transaction data and the neo-node can read our request.

2022-04-27 16:44 UTC, csmuller commented on core/src/test/java/io/neow3j/protocol/core/witnessrule/WitnessRuleTest.java
> +public class WitnessRuleTest extends ResponseTester {
😨 All these tests. The burden... Good work!

2022-04-28 09:18 UTC, mialbu commented on core/src/main/java/io/neow3j/transaction/witnessrule/AndCondition.java
> +    public io.neow3j.protocol.core.witnessrule.WitnessCondition toJson() {
I agree. So, we both win! ^^

2022-04-29 07:21 UTC, csmuller approved these changes

2022-04-29 07:24 UTC, merged